# CM hardware
BOARD_HARDWARE_CLASS := $(LOCAL_PATH)/cmhw

# LightHAL
TARGET_PROVIDES_LIBLIGHT := true

# init.rc
TARGET_PROVIDES_INIT_RC := true

# RIL
BOARD_RIL_CLASS := ../../../device/elephone/p8000/ril
BOARD_CONNECTIVITY_MODULE := conn_soc

# GPS
BOARD_GPS_LIBRARIES :=true
BOARD_MEDIATEK_USES_GPS := true

# Camera
USE_CAMERA_STUB := true

# Charger
BOARD_CHARGER_SHOW_PERCENTAGE := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(LOCAL_PATH)/bluetooth

# WiFi
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA:= STA
WIFI_DRIVER_FW_PATH_AP:= AP
WIFI_DRIVER_FW_PATH_P2P:= P2P
WPA_SUPPLICANT_VERSION := VER_0_8_X

# MTK audio
TARGET_CPU_MEMCPY_OPT_DISABLE := true
BOARD_USES_MTK_AUDIO := true

